### ISSUE TITLE
docker file access error

### ISSUE THREAD

**Issue by alenauus** [LucasFidon/trustworthy-ai-fetal-brain-segmentation#2]
hi Lucas,

thank you for sharing your work!

I got this file error (I also tried to download it in the browser but it does not work):

Step 19/30 : RUN cd third-party/nnUNet_trained_models/nnUNet/3d_fullres     && gdown https://drive.google.com/uc\?export\=download\&id\=1d42VyRZHhSNxKEPQldDqcIaeReX78jfY
 ---> Running in b405ae3f5281
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

Alena

**Comment by LucasFidon** [comment]
Hi Alena,
Thank you for reporting this error.
I will update the repository by the end of January.
Best,
Lucas

**Comment by LucasFidon** [comment]
Hi Alena,

You are right the files did not exist anymore at this location (I don't know why...)

I have re-uploaded the trained nnU-Net models to a new gdrive folder and updated the link in the docker file. The download should work now.

Also if the problem persists please make sure to update gdown to the lastest version. I have experienced the same error even when the files exist and the authorization is correctly set when using an older version of gdown (4.4.0).

Let me know if you have any other questions.

Best,
Lucas
