### ISSUE TITLE
difference between gift-surg/FetalBrainParcellation and this repo

### ISSUE THREAD

**Issue by daviddmc** [LucasFidon/trustworthy-ai-fetal-brain-segmentation#4]
Thanks for sharing your work.
I wonder what is the difference between this repo and gift-surg/FetalBrainParcellation.
It seems that both are based on the same twai paper. Which one do you recommend using?

**Comment by LucasFidon** [comment]
Hi, thank you for your interest in our work.
You are correct. I would recommend to use this repository.

**Comment by tvercaut** [comment]
I've archived https://github.com/gift-surg/FetalBrainParcellation to clarify -> closing the issue
