### ISSUE TITLE
where is batchgenerators?

### ISSUE THREAD

**Issue by DemerzelWang** [LucasFidon/trustworthy-ai-fetal-brain-segmentation#5]
Hi, I noticed that in the default_data_augmentation.py there are lines like from batchgenerators import ...., HOWEVER I didn't notice the existence of this file, and it rises to error when I tried to fine-tune on the nnUNet with command :"nnUNet_train 3d_fullres nnUNetTrainerV2_DRO_IS 50 1 -c ", could you please tell me how to solve this problem? I am more than delighted to hear your response!!

**Comment by LucasFidon** [comment]
Hi, thanks for your interest in our work.

batchgenerators is a python dependency available on pypi (you need version 0.21.0 to use with the version of nnUNet I use)
https://pypi.org/project/batchgenerators/0.21/

It is a dependencies of the version of nnUNet I have used to train the models, see:
https://github.com/LucasFidon/trustworthy-ai-fetal-brain-segmentation/blob/38cf1fb77bc896d133941b8f5388ef18feb2cae7/docker/third-party/nnUNet/setup.py#L18

I hope it helps! 

Lucas

**Comment by DemerzelWang** [comment]
Thanks a lot!! That helps a lot! I am so stupid hhhh
